name: Build

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14.x
    - run: npm install
    - run: xvfb-run -a npm test

  deploy:
    needs: [build]
    if: ${{ startsWith(github.event.ref, 'refs/tags/v') && needs.build.result == 'success' }}
    runs-on: ubuntu-latest
    name: Release Extension
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14

    - name: Build
      run: npm ci

    - name: Package extension
      run: npx vsce package

    - name: Publish extensions
      run: npx vsce publish --pat ${{ secrets.VS_MARKETPLACE_TOKEN }}
      if: runner.os == 'Linux'
